config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/about', to: "pages#about"

  resources :recepy_books do
    resources :recepies, except: %i[ index ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recepy
end

app/models/recepy.rb
class Recepy < ApplicationRecord
  belongs_to :recepy_book
  has_many :ingredients
  has_many :steps

  scope :my_recepies, -> (recepy_book) { where(recepy_book_id: recepy_book )} 
end

app/models/recepy_book.rb
class RecepyBook < ApplicationRecord
  has_many :recepies
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recepy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/recepies_controller.rb
class RecepiesController < ApplicationController
  before_action :set_recepy_book, only: %i[ show new create ]
  
  def show
    @recepy = @recepy_book.recepies.find(params[:id])
  end

  def new
    @recepy = @recepy_book.recepies.build
  end

  def create
    @recepy = @recepy_book.recepies.build(recepy_params)

    if @recepy.save
      redirect_to recepy_book_recepy_path(@recepy)
    else
      redirect_to @recepy_book
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_recepy_book
    @recepy_book = RecepyBook.find(params[:recepy_book_id])
  end

  def recepy_params
    params.require(:recepy).permit(:title, :preparation_time, :portion)
  end
end

app/controllers/recepy_books_controller.rb
class RecepyBooksController < ApplicationController
  before_action :set_recepy_book, only: %i[ show edit update destroy ]

  def index
    @recepy_books = RecepyBook.all
  end

  def show
    @recepies = Recepy.all.my_recepies(@recepy_book)
  end

  def new
    @recepy_book = RecepyBook.new
  end

  def create
    @recepy_book = RecepyBook.new(recepy_book_params)

    if @recepy_book.save
      redirect_to recepy_books_path, notice: 'Recepy Book created'
    else
      redirect_to new_recepy_book_path, alert: 'Deu ruim'
    end
  end

  def edit; end

  def update
    if @recepy_book.update(recepy_book_params)
      redirect_to recepy_books_path, notice: 'Recepy book edited'
    else
      redirect_to edit_recepy_book_path, alert: 'Deu ruim'
    end
  end

  def destroy
    @recepy_book.destroy
    redirect_to recepy_books_path
  end

  private

  def recepy_book_params
    params.require(:recepy_book).permit(:name)
  end

  def set_recepy_book
    @recepy_book = RecepyBook.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recepies_helper.rb
module RecepiesHelper
end

app/helpers/recepy_books_helper.rb
module RecepyBooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecepyBookApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<%= link_to 'Recepy Books', recepy_books_path %>

app/views/recepies/_form.html.erb
<%= form_with(model: [@recepy_book, @recepy]) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :preparation_time %>
    <%= f.number_field :preparation_time %>
  </div>

  <div>
    <%= f.label :portion %>
    <%= f.number_field :portion %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/recepies/edit.html.erb
<h1>Recepies#edit</h1>
<p>Find me in app/views/recepies/edit.html.erb</p>

app/views/recepies/new.html.erb
<h1>Recepies#new</h1>
<p>Find me in app/views/recepies/new.html.erb</p>

<%= render 'form' %>

app/views/recepies/show.html.erb
<h1><%= @recepy.title %></h1>

<div>
    <strong>Preparation time: </strong>
    <span><%= @recepy.preparation_time %></span>
</div>

<div>
    <strong>Portions: </strong>
    <span><%= @recepy.portion %></span>
</div>

app/views/recepy_books/_form.html.erb
<%= form_with(model: @recepy_book) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/recepy_books/edit.html.erb
<h1>RecepyBooks#edit</h1>
<%= render 'form' %>

app/views/recepy_books/index.html.erb
<h1>RecepyBooks</h1>

<ul>
  <li><%= link_to 'new', new_recepy_book_path %></li>
</ul>


<ul>
  <% @recepy_books.each do |recepy_book| %>
    <li>
      <span><%= link_to recepy_book.name, recepy_book %></span>
      <span><%= link_to 'edit', edit_recepy_book_path(recepy_book) %></span>
      <span><%= button_to 'destroy', recepy_book, method: :delete %></span>
    </li>
  <% end %>
</ul>

app/views/recepy_books/new.html.erb
<h1>RecepyBooks#new</h1>

<%= render 'form' %>

app/views/recepy_books/show.html.erb
<h1><%= @recepy_book.name %></h1>

<%= link_to 'New Recepy', new_recepy_book_recepy_path(@recepy_book) %>

<ul>
  <% @recepies.each do |recepy| %>
    <li>
      <span><%= link_to recepy.title, recepy_book_recepy_path(recepy) %></span>
    </li>
  <% end %>
</ul>